# Basic
title: 倩倩
subtitle: Juby's blog
description: 搴汀洲兮杜若 将以遗兮远者
url: "http://jubeny.com"

# Comment
comment:
    #disqus: jubytschu
    valine: true

# Social
social:
    mail: juby@jubeny.com

# Google Analytics
ga:
    id: UA-112090731-1
    host: auto  


# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _post/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------


permalink: /:year/:month/:title.html
# Format
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable: true

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear #背景Mask

# The blog button should not be removed.
blog_button:
    title: 主页
    description: blog

# Navigation buttons in the front page.s
nav:
    - {title: 存档, description: archive, url: '/archive.html'}   
    - {title: 标签, description: tags, url: '/tags.html'}
    - {title: 留言, description: guestbook, url: '/guestbook.html'}      
    - {title: 关于, description: about, url: '/about.html'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 9
paginate_path: "page/:num/"


