# Basic
title: 渚碧
author: Juby
url: https://jubeny.com
timezone: Asia/Shanghai

# SEO
keywords: [Juby, 渚碧, 读书, なぎさ]
description: 我欲种菜 亦植蔷薇

# Social
social:
  twitter: jubyshu
  weibo: manatsuakimoto
  spotify: ybaichfkjx5z3yyu2d6s2ocyp

# Google
google: 
  analytics: UA-112090731-1
  # adsense: ca-pub-1918559515694686
  site_verification: lTL7MkDxY16gNmRWyqoZYflJgECNQkxPjyFoYgM3z2M

# Baidu
baidu:
  site_verification: 99xvWiquex

#Bing
bing: 
  site_verification: 10BEE8610C0E89AB722E5862C2C5CB0F

# Leancloud used for Valine
leancloud: 
  appid: CRU9WNiFOXtffNHePc2WD4sT-gzGzoHsz
  appkey: YsaHf3ahdzk2NkPOmNBohvgd

# OpenGraph & TwitterCard
card: /images/default/tcard.png

# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _posts/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------

# Permalink
permalink: '/:year/:month/:title/'

# Format
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Navigation buttons in the front page.s
nav:
  - {title: 主页, description: blog, url: '/'}
  - {title: 存档, description: archive, url: '/archive/'}   
  - {title: 读书, description: read, url: '/book/'}
  - {title: 留言, description: guestbook, url: '/guestbook/'}      
  - {title: 关于, description: about, url: '/about/'}         

# Categories
categs:
  - {title: 诗, url: '/poetry/'}
  - {title: 文, url: '/essay/'}
  - {title: 评, url: '/review/'}
  - {title: 说, url: '/story/'}

# Pagination
plugins: [jekyll-paginate-v2, jekyll-sitemap]
# paginate: 9
# paginate_path: '/page/:num/'
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Increase jekyll build speed
exclude: [Gemfile, Gemfile.lock, README.md]
keep_files: [images]
incrumental: true

# Collections
collections:
  notes:
    output: true

# Redirect
include: [_redirects]