# Basic
title: 渚碧
author: Juby
url: https://jubeny.com
timezone: Asia/Shanghai

# SEO
keywords: [渚碧, 未木大, 纯文学爱好者, 日语学习, 读书笔记, 永远追求自由]
description: 我欲種菜 亦植薔薇

# Social
social:
  twitter: jubyshu
  weibo: soulinsight
  youtube: UCg-mkLHhCiWZfc2TLlBuR8A

# Google
google: 
  analytics: UA-112090731-1
  site_verification: lTL7MkDxY16gNmRWyqoZYflJgECNQkxPjyFoYgM3z2M

# Leancloud used for Valine
leancloud: 
  appid: QSgMGPbA7GNASFnb69vrBVxT-MdYXbMMI
  appkey: 5LnIvn6xAMPXGlMAssqbQCB6

# disqus
# disqus_js: https://juby.disqus.com/embed.js
# OpenGraph & TwitterCard
card: /images/tcard.png

# ---------------------上面信息改为自己的-------------------------
# 
#          jekyll文档参考: https://jekyllrb.com/docs/
#
# ---------------------下面信息视情况更改-------------------------

# Permalink
permalink: '/:year/:month/:title/'

# Format
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Navigation buttons
nav:
  - {title: 主頁, description: blog, url: '/'}
  - {title: 存檔, description: archive, url: '/archive/'}   
  - {title: 讀書, description: read, url: '/book/'}
  - {title: 留言, description: guestbook, url: '/guestbook/'}      
  - {title: 關於, description: about, url: '/about/'}         

# Categories
categs:
  - {title: J, description: 日誌, url: '/journal/'}
  - {title: E, description: 隨筆,url: '/essay/'}
  - {title: R, description: 評論,url: '/review/'}
  - {title: P, description: 詩歌,url: '/poetry/'}
  - {title: S, description: 故事,url: '/story/'}

# Plugins
plugins: [jekyll-paginate-v2, jekyll-sitemap, jekyll-algolia]

# Pagination
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# autopage_tags
autopages:
  enabled: true
  categories: 
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts: 
      - 'autopage_tags.html'
    title: '標籤 - :tag'
    permalink: '/tags/:tag'

# algolia search
algolia:
  application_id: XTX1EOVMI5
  index_name: jubeny
  search_only_api_key: c05381f747c5207b6dd655ca29e18fce

# Increase jekyll build speed
exclude: [Gemfile, Gemfile.lock, README.md]
keep_files: [images]
incrumental: true

# Redirect
include: [_redirects]