# Basic
title: 渚碧
description: 种菜的时候，也想种点玫瑰
url: https://jubeny.com
author: Juby
banner: https://jubeny.com/images/default/tcard.png

# Comment
comment:
  valine: true

# Social
social:
  twitter: jubyshu

# Google Analytics
ga:
  id: UA-112090731-1
  host: auto

# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _post/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------

permalink: "/:year/:month/:title/"
# Format
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: _sass
  style: compressed

# The blog button should not be removed.
blog_button:
  title: 主页
  description: blog

# Navigation buttons in the front page.s
nav:
  - {title: 主页, description: blog, url: '/#blog'}
  - {title: 存档, description: archive, url: '/archive/'}   
  - {title: 标签, description: tags, url: '/tags/'}
  - {title: 读书, description: read, url: '/read/'}
  - {title: 留言, description: guestbook, url: '/guestbook/'}      
  - {title: 关于, description: about, url: '/about/'}         

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 9
paginate_path: page/:num/
