---
title: 渚碧
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 种菜的时候，也想种点玫瑰
url: https://jubeny.com
comment:
  valine: true
ga:
  id: UA-112090731-1
  host: auto
permalink: "/:year/:month/:title.html"
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
blog_button:
  title: 主页
  description: blog
nav:
- title: 存档
  description: archive
  url: "/archive.html"
- title: 标签
  description: tags
  url: "/tags.html"
- title: 留言
  description: guestbook
  url: "/guestbook.html"
- title: 关于
  description: about
  url: "/about.html"
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 9
paginate_path: page/:num/
