# Basic
title: 渚碧
author: Juby
url: https://jubeny.com
timezone: Asia/Shanghai
build_date: 2015/01/03 23:15:15

# SEO
keywords: [渚碧, Juby, 爱好纯文学, 学习日语, 读书笔记, 自由主义, 骑行]
description: 我欲种菜 亦植蔷薇

# Social
social:
  twitter: fermatslibrary
  instagram: liverpoolfc
  youtube: UCNUS6e1M0eUIv1F88kxRJ-g

# Disqus
disqus: 
  shortname: juby
  sitename: AoiNagisa
  apikey: dXc0vOCZ1LAX0c9y3FB0fpC5KA7L56QEFDYRXaUeAyvCzowv8hKQRzpsG6ITpxSL
  admin: mikihiro
  mod: Mod
  nocomment: Hello? Is there anybody in there?

# Google
# google: 
#   analytics: UA-112090731-1
#   site_verification: lTL7MkDxY16gNmRWyqoZYflJgECNQkxPjyFoYgM3z2M

# clicky site id
# clicky: 101359865

# OpenGraph & TwitterCard
card: /images/tcard.webp

# algolia search
algolia:
  application_id: XTX1EOVMI5
  index_name: jubeny
  search_only_api_key: c05381f747c5207b6dd655ca29e18fce

# mailchimp link
mailchimp: jubeny.us19.list-manage.com/subscribe/post?u=d8acca80de6498b2cd55b8cae&amp;id=aeb4f65fa7

# Navigation buttons
nav:
  - {title: 首页, description: blog, url: '/'}
  - {title: 历史, description: archive, url: '/archive/'}   
  - {title: 读书, description: book, url: '/book/'}
  - {title: 留言, description: guestbook, url: '/guestbook/'}      
  - {title: 关于, description: about, url: '/about/'}         

# Categories
categs:
  - {title: J, description: 日志, url: '/journal/'}
  - {title: E, description: 随笔,url: '/essay/'}
  - {title: R, description: 评论,url: '/review/'}
  - {title: P, description: 诗歌,url: '/poetry/'}
  - {title: S, description: 故事,url: '/story/'}


# ---------------------上面信息改为自己的-------------------------
# 
#          jekyll文档参考: https://jekyllrb.com/docs/
#
# ---------------------下面信息视情况更改-------------------------


# Permalink
permalink: '/:year/:month/:title/'

# Format
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins: [jekyll-paginate-v2, jekyll-sitemap, jekyll-algolia]

# Pagination
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# autopage_tags
autopages:
  enabled: true
  categories: 
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts: 
      - 'autopage_tags.html'
    title: '标签 - :tag'
    permalink: '/tags/:tag'

# Increase jekyll build speed
exclude: [Gemfile, Gemfile.lock, README.md]
keep_files: [images]
incrumental: true

# Redirect
include: [_redirects]